name = "satyam-gold"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "satyamgold-production"
database_id = ""
